### ISSUE TITLE
Is this fully working?

### ISSUE THREAD

**Issue by vvavepacket** [mikepugh/react-native-aws-pinpoint#1]
Is this working? What functionalities are included. Thank you.

**Comment by mikepugh** [comment]
No - I created this shell project for something but ended up going a different route.

**Comment by vvavepacket** [comment]
Is there any alternqtive for this for react native?

**Comment by mikepugh** [comment]
Check this out https://aws.amazon.com/blogs/mobile/targeted-push-notifications-and-campaign-management-using-amazon-pinpoint-and-react-native/
